[Team-A1] #8 Gas and break pedal implementation
SzFMV2021-Osz/AutomatedCar-A pull request #13
Opened 2021-09-28 23:34 UTC by nnorbi3

2021-09-30 06:33 UTC, jozdavab requested changes
Észrevétel:

- Ha elkezdek gyorsítani és elengedem az előrét akkor a kamera elmarad a kocsitól.
- Ha átváltok a másik autóra, rossz irányba mozog az előre gombot lenyomva.

Kérdés: 
- Game.cs ben mi ez a sok kivett elágazás (debughoz, rotatehez)? Nem vesztünk funkciót?
- Unit testing?

Nitpicking:
- Azonos changet tartalmozó commitokat squasholni lehetne a jobb olvashatóságért

2021-09-30 16:30 UTC, nnorbi3 commented
@jozdavab 
- A kamera lockot lecsekkolom
- A mozgas egyelore Y tengelyu, mert a kormanyzast implementalo ticketnel jon kepbe az auto orientacioja, illetve ez csak alapkent szolgal a tobbi funkcionak
- A Game.cs-bol azert vettem ki az input kezelest mert a MainWindows.xml.cs -ben mar implementalva van (nehany extra gombbal kiegeszitve), emiatt a Game timer elinditasa utan duplan lett volna lekezelve az input
- Unit teszt lesz (koszi, ezt elfelejtettem 😄)
- A squash-al kifejezetten nem ertek egyet, direkt olyan commit-okkal dolgozom amik jol elkulonithetok es szerintem sokkal jobb ha commit szinten visszakovetheto, ezaltal tiszta a history. Kesobbi bugoknal, furcsasagoknal hasznos lehet ha commit-by-commit tudunk turkalni.

2021-10-01 13:54 UTC, jozdavab approved these changes
Nekem jónak tűnik.

Kérdés:
Ha satuféket nyomok, utána elkezdek gyorsítani padlógázzal, akkor megy az autó (de lassan)
Ez véletlen, vagy intended, és "works as designed"?

Sidenote:
Squash comittot továbbra is javasolnám egyébként.
Szerintem is jók ha egymástól elkülöníthetőek a commitok, de a squasholás pont ezt segíti elő olyan esetekben amikor egymást fixáló/módosító commitokat teszünk egybe. Értelemszerűen nem az összeset, hanem csak a logikailag egymáshoz tartozóakat

2021-10-01 16:55 UTC, nnorbi3 commented
En nem vettem eszre a jelenseget, de gazadas-fekezes a gyorsulasnak megfeleloen mukodik, igy ha ilyet eszlelsz akkor works as intended.

2021-10-05 07:31 UTC, kerteszgabor approved these changes
Szerintem egyelőre teljesen ok, szükség lenne ennek a mergelésére, hogy tudjunk tovább haladni a többi feladattal

2021-10-06 05:31 UTC, DaKul28 approved these changes
Alapnak teljesen jó, majd ha szükséges bővítjük más branchen.

2021-10-06 05:50 UTC, merged